import type { Metadata } from "next";
import Link from "next/link";
import { PolicyPage, type PolicySection } from "@/components/site/policy-page";
import { getSettings } from "@/lib/data";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing use of the academy website, courses and learning platform." };

export default async function TermsPage() {
  const settings = await getSettings();
  const email = settings.supportEmail || "our support team";
  const sections: PolicySection[] = [
    { id: "acceptance", title: "Accepting these terms", content: <><p>By creating an account, enrolling on a course, making a payment or using the learning platform, you agree to these Terms and our <Link href="/privacy">Privacy Policy</Link>. If you do not agree, do not use the services.</p><p>You must be at least 18, or have permission from a parent or legal guardian who accepts these Terms for you.</p></> },
    { id: "accounts", title: "Accounts and security", content: <><p>Provide accurate information and keep it up to date. You are responsible for activity under your account and for keeping your password confidential.</p><ul><li>Do not share login details or allow another person to attend in your place.</li><li>Tell us promptly if you believe your account has been compromised.</li><li>We may verify identity where necessary to protect students and payments.</li></ul></> },
    { id: "enrolment", title: "Enrolment and cohort places", content: <><p>A place is confirmed only when we accept your enrolment and any required payment has cleared. Cohort dates, capacity, teaching format and prerequisites are shown on the relevant course page.</p><p>We may refuse or cancel an enrolment where information is inaccurate, payment is unauthorised, a cohort is full, or participation would create a safety or safeguarding risk.</p></> },
    { id: "payments", title: "Fees and payments", content: <><p>Prices are shown in the selected currency and include applicable taxes unless stated otherwise. Payments may be processed by third-party providers such as Stripe, Paystack or pawaPay, whose own terms also apply.</p><p>You remain responsible for bank charges, exchange-rate differences and agreed instalments. Refund eligibility is explained in our <Link href="/refund-policy">Refund Policy</Link>.</p></> },
    { id: "delivery", title: "Classes, changes and attendance", content: <><p>Classes may be live online, in person or hybrid. You are responsible for suitable equipment, connectivity and travel where applicable.</p><p>We may reasonably change an instructor, venue, joining link or timetable. If we cancel or materially reschedule a cohort, we will offer an appropriate alternative, credit or refund.</p></> },
    { id: "conduct", title: "Student conduct", content: <><p>Treat instructors, staff and other learners respectfully. Harassment, discrimination, threats, cheating, disruption, unlawful activity and attempts to bypass platform security are prohibited.</p><p>We may remove content, restrict access or end an enrolment for serious or repeated misconduct. Where reasonably possible, we will explain the concern first.</p></> },
    { id: "course-materials", title: "Course materials and intellectual property", content: <><p>Course videos, slides, templates, exercises and platform content belong to {settings.siteName} or its licensors. Enrolment gives you a personal, limited, non-transferable licence to use them for learning.</p><p>You may not resell, publish, share, record or systematically copy materials without written permission. You retain ownership of original work you submit, while giving us permission to review and store it to deliver the course.</p></> },
    { id: "recordings", title: "Recordings and participation", content: <><p>Online classes may be recorded for enrolled learners. We will notify participants when recording is active. Avoid sharing sensitive personal information during recorded sessions.</p><p>Your display name, voice or contributions may appear in a recording. Contact us before class if you need a reasonable alternative.</p></> },
    { id: "availability", title: "Platform availability", content: <><p>We aim to keep the platform reliable but cannot promise uninterrupted access. Maintenance, internet failures and third-party services may occasionally affect availability.</p><p>We may update features and course materials to improve the service, security or curriculum.</p></> },
    { id: "liability", title: "Our responsibility", content: <><p>We provide education and support, but do not guarantee employment, promotion, income, certification by a third party or a particular result.</p><p>Nothing in these Terms excludes liability that cannot lawfully be excluded. Otherwise, our total liability relating to a paid course will not exceed the amount you paid for that course.</p></> },
    { id: "ending-access", title: "Suspension and termination", content: <><p>You may stop using your account at any time. We may suspend or close access for material breach, non-payment, fraud, security risk or unlawful conduct.</p><p>Clauses relating to payment, intellectual property, liability and dispute resolution continue after access ends where relevant.</p></> },
    { id: "law-contact", title: "Governing law and contact", content: <><p>These Terms are governed by the laws of England and Wales, and disputes are subject to the courts of England and Wales, except where consumer law in your country gives you mandatory rights.</p><p>Questions or legal notices can be sent to <a href={`mailto:${email}`}>{email}</a>{settings.address ? ` or ${settings.address}` : ""}.</p></> },
  ];
  return <PolicyPage eyebrow="Legal" title="Terms of Use" summary="The agreement governing academy accounts, enrolment, live classes, payments and use of our learning platform." updated="27 September 2026" sections={sections} settings={settings} />;
}
